# Generated by Django 6.0.6 on 2026-06-14 20:24

import config.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=config.uploads.UploadToUUID('avatars'), verbose_name='foto de perfil'),
        ),
    ]
