# Generated by Django 6.0.6 on 2026-06-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('jefe_punto', 'Jefe de punto'), ('cajero', 'Cajero'), ('comprador', 'Comprador')], default='comprador', max_length=20, verbose_name='rol'),
        ),
    ]
