# Generated by Django 6.0.6 on 2026-06-15 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_role_user_to_comprador'),
        ('inventory', '0002_seed_initial_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='inventory.warehouse', verbose_name='bodega asignada'),
        ),
    ]
