# Generated by Django 6.0.6 on 2026-06-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_warehouse'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventory', '0003_transfer_transferitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='número de identificación'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_type',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('NIT', 'NIT'), ('PP', 'Pasaporte'), ('TI', 'Tarjeta de identidad')], default='', max_length=8, verbose_name='tipo de identificación'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='correo electrónico'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('id_number__gt', '')), fields=('id_number',), name='unique_id_number_when_set'),
        ),
    ]
