# Generated by Django 6.0.6 on 2026-06-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_options_user_id_number_user_id_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_walk_in',
            field=models.BooleanField(default=False, verbose_name='consumidor final (mostrador)'),
        ),
    ]
