# Generated by Django 6.0.6 on 2026-06-12 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, max_length=220, verbose_name='slug')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='SKU')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='imagen principal')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='precio de costo')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='precio de venta')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='existencias')),
                ('color', models.CharField(blank=True, max_length=60, verbose_name='color')),
                ('size', models.CharField(blank=True, max_length=60, verbose_name='talla')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='fecha de vencimiento')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='imagen')),
                ('alt_text', models.CharField(blank=True, max_length=160, verbose_name='texto alternativo')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'imagen de producto',
                'verbose_name_plural': 'imágenes de producto',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, max_length=140, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalog.category', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'subcategoría',
                'verbose_name_plural': 'subcategorías',
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.subcategory', verbose_name='subcategoría'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_subcategory_name_per_category'),
        ),
    ]
