# Generated by Django 6.0.6 on 2026-06-12 18:54

from django.db import migrations

# Tallas estándar (orden de menor a mayor).
SIZES = ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL']

# Colores básicos para arrancar; el admin puede añadir más.
COLORS = [
    ('Negro', '#000000'),
    ('Blanco', '#FFFFFF'),
    ('Gris', '#808080'),
    ('Rojo', '#FF0000'),
    ('Azul', '#0000FF'),
    ('Verde', '#008000'),
    ('Amarillo', '#FFFF00'),
    ('Naranja', '#FFA500'),
    ('Rosado', '#FFC0CB'),
    ('Morado', '#800080'),
    ('Café', '#8B4513'),
    ('Beige', '#F5F5DC'),
]


def seed(apps, schema_editor):
    Size = apps.get_model('catalog', 'Size')
    Color = apps.get_model('catalog', 'Color')
    for i, name in enumerate(SIZES):
        Size.objects.get_or_create(name=name, defaults={'position': i})
    for name, hex_code in COLORS:
        Color.objects.get_or_create(name=name, defaults={'hex_code': hex_code})


def unseed(apps, schema_editor):
    Size = apps.get_model('catalog', 'Size')
    Color = apps.get_model('catalog', 'Color')
    Size.objects.filter(name__in=SIZES).delete()
    Color.objects.filter(name__in=[c[0] for c in COLORS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_color_size_alter_product_color_alter_product_size'),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
