# Generated by Django 6.0.6 on 2026-06-13 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_seed_sizes_and_colors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['position', 'id'], 'verbose_name': 'imagen de producto', 'verbose_name_plural': 'imágenes de producto'},
        ),
    ]
