# Generated by Django 6.0.6 on 2026-06-13 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_productimage_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productimage',
            name='one_main_image_per_product',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='is_main',
        ),
    ]
