# Generated by Django 6.0.6 on 2026-06-13 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_productimage_one_main_image_per_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.PositiveSmallIntegerField(choices=[(19, 'IVA 19%'), (5, 'IVA 5%'), (0, 'Excluido / 0%')], default=19, verbose_name='IVA (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kilogramo'), ('g', 'Gramo'), ('lb', 'Libra'), ('l', 'Litro'), ('ml', 'Mililitro'), ('paquete', 'Paquete'), ('caja', 'Caja'), ('docena', 'Docena')], default='unidad', max_length=10, verbose_name='unidad de medida'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.brand', verbose_name='marca'),
        ),
    ]
