# Generated by Django 6.0.6 on 2026-06-13 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_brand_product_tax_rate_product_unit_of_measure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, default='', max_length=14, verbose_name='código de barras')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='precio de costo')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='precio de venta')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='existencias')),
                ('min_stock', models.PositiveIntegerField(default=0, verbose_name='stock mínimo')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='catalog.color', verbose_name='color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='producto')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='catalog.size', verbose_name='talla')),
            ],
            options={
                'verbose_name': 'variante de producto',
                'verbose_name_plural': 'variantes de producto',
                'ordering': ['product', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('barcode__gt', '')), fields=('barcode',), name='unique_barcode_when_set')],
            },
        ),
    ]
