# Generated by Django 6.0.6 on 2026-06-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_product_color_remove_product_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='average_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='costo promedio'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='precio de costo de referencia'),
        ),
    ]
