# Generated by Django 6.0.6 on 2026-06-14 20:24

import config.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_variant_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantimage',
            name='image',
            field=models.ImageField(upload_to=config.uploads.UploadToUUID('variants'), verbose_name='imagen'),
        ),
    ]
