# Generated by Django 6.0.6 on 2026-06-23 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_remove_productvariant_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='nombre')),
                ('has_swatch', models.BooleanField(default=False, verbose_name='usa color')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'atributo del catálogo',
                'verbose_name_plural': 'atributos del catálogo',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.AddField(
            model_name='productattribute',
            name='definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_attributes', to='catalog.attributedefinition', verbose_name='atributo del catálogo'),
        ),
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=80, verbose_name='valor')),
                ('swatch_hex', models.CharField(blank=True, default='', max_length=7, verbose_name='HEX')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.attributedefinition', verbose_name='atributo')),
            ],
            options={
                'verbose_name': 'opción de atributo',
                'verbose_name_plural': 'opciones de atributo',
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('definition', 'value'), name='unique_option_per_definition')],
            },
        ),
    ]
