# Generated by Django 6.0.6 on 2026-06-15 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('label', models.CharField(blank=True, default='', max_length=60, verbose_name='etiqueta')),
                ('recipient', models.CharField(max_length=160, verbose_name='destinatario')),
                ('phone', models.CharField(blank=True, default='', max_length=40, verbose_name='teléfono')),
                ('line1', models.CharField(max_length=200, verbose_name='dirección')),
                ('city', models.CharField(blank=True, default='', max_length=120, verbose_name='ciudad')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='indicaciones')),
                ('is_default', models.BooleanField(default=False, verbose_name='predeterminada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'dirección',
                'verbose_name_plural': 'direcciones',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('kind', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('nequi', 'Nequi'), ('transferencia', 'Transferencia'), ('efectivo', 'Efectivo contra entrega'), ('otro', 'Otro')], max_length=20, verbose_name='tipo')),
                ('label', models.CharField(max_length=80, verbose_name='alias')),
                ('is_default', models.BooleanField(default=False, verbose_name='predeterminado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'método de pago',
                'verbose_name_plural': 'métodos de pago',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
    ]
