# Generated by Django 6.0.6 on 2026-06-23 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_variantimage_image'),
        ('inventory', '0003_transfer_transferitem'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('number', models.PositiveIntegerField(editable=False, unique=True, verbose_name='número')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=12, verbose_name='estado')),
                ('fulfillment', models.CharField(choices=[('envio', 'Envío a domicilio'), ('recoge', 'Recoge en el punto')], default='envio', max_length=10, verbose_name='entrega')),
                ('payment_method', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('nequi', 'Nequi'), ('transferencia', 'Transferencia'), ('efectivo', 'Efectivo contra entrega')], max_length=20, verbose_name='forma de pago')),
                ('is_paid', models.BooleanField(default=False, verbose_name='pagado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='subtotal sin IVA')),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='total')),
                ('ship_recipient', models.CharField(blank=True, default='', max_length=160, verbose_name='destinatario')),
                ('ship_phone', models.CharField(blank=True, default='', max_length=40, verbose_name='teléfono')),
                ('ship_line1', models.CharField(blank=True, default='', max_length=200, verbose_name='dirección')),
                ('ship_city', models.CharField(blank=True, default='', max_length=120, verbose_name='ciudad')),
                ('ship_notes', models.CharField(blank=True, default='', max_length=255, verbose_name='indicaciones')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='nota del comprador')),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='motivo de cancelación')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmado el')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='enviado el')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='entregado el')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelado el')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_orders', to=settings.AUTH_USER_MODEL, verbose_name='gestionado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='comprador')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='inventory.warehouse', verbose_name='punto')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='descripción')),
                ('sku', models.CharField(blank=True, default='', max_length=64, verbose_name='SKU')),
                ('quantity', models.PositiveIntegerField(verbose_name='cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='precio unitario')),
                ('tax_rate', models.PositiveSmallIntegerField(default=0, verbose_name='IVA (%)')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='costo unitario')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='total línea')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order', verbose_name='pedido')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.productvariant', verbose_name='variante')),
            ],
            options={
                'verbose_name': 'línea de pedido',
                'verbose_name_plural': 'líneas de pedido',
                'ordering': ['id'],
            },
        ),
    ]
