# Generated by Django 6.0.6 on 2026-06-23 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_seed_colombia'),
        ('store', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='geo.country', verbose_name='país'),
        ),
        migrations.AddField(
            model_name='address',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='geo.department', verbose_name='departamento'),
        ),
        migrations.AddField(
            model_name='order',
            name='ship_country',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='país'),
        ),
        migrations.AddField(
            model_name='order',
            name='ship_department',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='departamento'),
        ),
        migrations.AddField(
            model_name='order',
            name='ship_phone_alt',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='teléfono secundario'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='geo.city', verbose_name='ciudad'),
        ),
    ]
