# Generated by Django 6.0.6 on 2026-06-28 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_seed_attribute_catalog'),
        ('inventory', '0006_warehouse_latitude_warehouse_longitude'),
        ('store', '0005_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitud'),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitud'),
        ),
        migrations.CreateModel(
            name='OrderAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='cantidad')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='costo unitario')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='store.order', verbose_name='pedido')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_allocations', to='catalog.productvariant', verbose_name='variante')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_allocations', to='inventory.warehouse', verbose_name='bodega')),
            ],
            options={
                'verbose_name': 'asignación de pedido',
                'verbose_name_plural': 'asignaciones de pedido',
                'ordering': ['id'],
            },
        ),
    ]
