# Generated by Django 6.0.6 on 2026-06-14 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0011_productvariant_average_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nombre')),
                ('code', models.CharField(blank=True, default='', max_length=20, verbose_name='código')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'bodega',
                'verbose_name_plural': 'bodegas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste_entrada', 'Ajuste (entrada)'), ('ajuste_salida', 'Ajuste (salida)'), ('transferencia', 'Transferencia')], max_length=20, verbose_name='tipo')),
                ('reason', models.CharField(blank=True, choices=[('compra', 'Compra'), ('venta', 'Venta'), ('saldo_inicial', 'Saldo inicial'), ('conteo_fisico', 'Conteo físico'), ('merma_dano', 'Merma / daño'), ('vencimiento', 'Vencimiento'), ('robo_perdida', 'Robo / pérdida'), ('transferencia', 'Transferencia'), ('correccion', 'Corrección'), ('otro', 'Otro')], default='', max_length=20, verbose_name='motivo')),
                ('quantity', models.PositiveIntegerField(verbose_name='cantidad')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='costo unitario')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='costo total')),
                ('balance_after', models.PositiveIntegerField(default=0, verbose_name='saldo resultante')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='nota')),
                ('reference', models.CharField(blank=True, default='', max_length=64, verbose_name='referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='catalog.productvariant', verbose_name='variante')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.warehouse', verbose_name='bodega')),
                ('warehouse_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='inventory.warehouse', verbose_name='bodega destino')),
            ],
            options={
                'verbose_name': 'movimiento de inventario',
                'verbose_name_plural': 'movimientos de inventario',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='existencias')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='catalog.productvariant', verbose_name='variante')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='inventory.warehouse', verbose_name='bodega')),
            ],
            options={
                'verbose_name': 'existencia por bodega',
                'verbose_name_plural': 'existencias por bodega',
                'ordering': ['warehouse__name'],
                'constraints': [models.UniqueConstraint(fields=('variant', 'warehouse'), name='unique_variant_per_warehouse')],
            },
        ),
    ]
