# Generated by Django 6.0.6 on 2026-06-15 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_variantimage_image'),
        ('inventory', '0002_seed_initial_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='número')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=12, verbose_name='estado')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='nota')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de resolución')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='inventory.warehouse', verbose_name='bodega destino')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='inventory.warehouse', verbose_name='bodega origen')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_requested', to=settings.AUTH_USER_MODEL, verbose_name='solicitada por')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_resolved', to=settings.AUTH_USER_MODEL, verbose_name='resuelta por')),
            ],
            options={
                'verbose_name': 'transferencia',
                'verbose_name_plural': 'transferencias',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='cantidad')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='costo unitario')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.transfer', verbose_name='transferencia')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_items', to='catalog.productvariant', verbose_name='variante')),
            ],
            options={
                'verbose_name': 'línea de transferencia',
                'verbose_name_plural': 'líneas de transferencia',
                'ordering': ['id'],
            },
        ),
    ]
