# Generated by Django 6.0.6 on 2026-06-28 15:57

import config.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_transfer_transferitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='correo'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='hours',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='horario de atención'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='map_embed_url',
            field=models.URLField(blank=True, default='', max_length=600, verbose_name='mapa (URL del iframe)'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='teléfono'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=config.uploads.UploadToUUID('warehouses'), verbose_name='foto'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='show_in_store',
            field=models.BooleanField(default=True, verbose_name='mostrar en la tienda'),
        ),
    ]
