# Generated by Django 6.0.6 on 2026-06-28 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_seed_colombia'),
        ('inventory', '0004_warehouse_description_warehouse_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='geo.city', verbose_name='ciudad'),
        ),
    ]
