# Generated by Django 6.0.6 on 2026-06-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_warehouse_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitud'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitud'),
        ),
    ]
