# Generated by Django 6.0.6 on 2026-06-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_warehouse_latitude_warehouse_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='schedule',
            field=models.JSONField(blank=True, default=dict, verbose_name='horario por día'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='hours',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='nota de horario'),
        ),
    ]
