# Generated by Django 6.0.6 on 2026-06-15 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0013_alter_variantimage_image'),
        ('inventory', '0002_seed_initial_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
                ('document', models.CharField(blank=True, default='', max_length=40, verbose_name='documento / NIT')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='correo')),
                ('phone', models.CharField(blank=True, default='', max_length=40, verbose_name='teléfono')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(editable=False, unique=True, verbose_name='número')),
                ('status', models.CharField(choices=[('completada', 'Completada'), ('anulada', 'Anulada')], default='completada', max_length=12, verbose_name='estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='subtotal sin IVA')),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='IVA')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='descuento')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='total')),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='pagado')),
                ('change', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='cambio')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='nota')),
                ('receipt_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='correo del recibo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='anulada el')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='vendedor')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.customer', verbose_name='cliente')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_sales', to=settings.AUTH_USER_MODEL, verbose_name='anulada por')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='inventory.warehouse', verbose_name='bodega')),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='descripción')),
                ('sku', models.CharField(blank=True, default='', max_length=64, verbose_name='SKU')),
                ('quantity', models.PositiveIntegerField(verbose_name='cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='precio unitario')),
                ('tax_rate', models.PositiveSmallIntegerField(default=0, verbose_name='IVA (%)')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='costo unitario')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='total línea')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='venta')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='catalog.productvariant', verbose_name='variante')),
            ],
            options={
                'verbose_name': 'línea de venta',
                'verbose_name_plural': 'líneas de venta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('otro', 'Otro')], max_length=20, verbose_name='forma de pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='monto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale', verbose_name='venta')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'ordering': ['id'],
            },
        ),
    ]
