# Generated by Django 6.0.6 on 2026-06-28 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_unify_customers_into_users'),
        ('store', '0005_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='channel',
            field=models.CharField(choices=[('pos', 'Punto de venta'), ('online', 'Tienda en línea')], default='pos', max_length=10, verbose_name='canal'),
        ),
        migrations.AddField(
            model_name='sale',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale', to='store.order', verbose_name='pedido'),
        ),
    ]
