# Generated by Django 6.0.6 on 2026-06-28 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Stockly', max_length=80, verbose_name='nombre del negocio')),
                ('tagline', models.CharField(blank=True, default='', max_length=180, verbose_name='eslogan')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='logo')),
                ('color_primary', models.CharField(default='#0e6e4e', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Usa un color hexadecimal, p. ej. #0e6e4e.')], verbose_name='color primario')),
                ('color_accent', models.CharField(default='#b8923a', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Usa un color hexadecimal, p. ej. #0e6e4e.')], verbose_name='color de acento')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='correo de contacto')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=40, verbose_name='teléfono de contacto')),
                ('contact_address', models.CharField(blank=True, default='', max_length=200, verbose_name='dirección')),
                ('nit', models.CharField(blank=True, default='', max_length=40, verbose_name='NIT')),
                ('instagram_url', models.URLField(blank=True, default='', verbose_name='Instagram')),
                ('facebook_url', models.URLField(blank=True, default='', verbose_name='Facebook')),
                ('whatsapp', models.CharField(blank=True, default='', max_length=40, verbose_name='WhatsApp')),
                ('footer_note', models.CharField(blank=True, default='', max_length=200, verbose_name='nota del pie')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuración del sitio',
                'verbose_name_plural': 'configuración del sitio',
            },
        ),
    ]
