# Generated by Django 6.0.6 on 2026-06-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='icono de pestaña (favicon)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='socials',
            field=models.JSONField(blank=True, default=list, verbose_name='redes sociales'),
        ),
    ]
