# Generated by Django 6.0.6 on 2026-06-29 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0002_remove_siteconfig_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='favicon',
            field=models.FileField(blank=True, null=True, upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(['png', 'svg', 'ico', 'jpg', 'jpeg', 'webp'])], verbose_name='icono de pestaña (favicon)'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'svg', 'gif'])], verbose_name='logo'),
        ),
    ]
