# Generated by Django 6.0.6 on 2026-06-29 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_seed_colombia'),
        ('siteconfig', '0003_alter_siteconfig_favicon_alter_siteconfig_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='contact_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='geo.city', verbose_name='ciudad'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='icono de marca'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='contact_address',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='dirección (calle)'),
        ),
    ]
