# Generated by Django 6.0.6 on 2026-06-29 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0004_siteconfig_contact_city_siteconfig_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='color_footer',
            field=models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator('^(?:#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6}))?$', 'Usa un color hexadecimal, p. ej. #0e6e4e.')], verbose_name='fondo del pie de página'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='color_hero',
            field=models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator('^(?:#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6}))?$', 'Usa un color hexadecimal, p. ej. #0e6e4e.')], verbose_name='fondo del hero de inicio'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='color_navbar',
            field=models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator('^(?:#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6}))?$', 'Usa un color hexadecimal, p. ej. #0e6e4e.')], verbose_name='fondo de la barra de navegación'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='color_page',
            field=models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator('^(?:#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6}))?$', 'Usa un color hexadecimal, p. ej. #0e6e4e.')], verbose_name='fondo general de la página'),
        ),
    ]
