# Generated by Django 6.0.6 on 2026-06-29 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0005_siteconfig_color_footer_siteconfig_color_hero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='color_announce',
            field=models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator('^(?:#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6}))?$', 'Usa un color hexadecimal, p. ej. #0e6e4e.')], verbose_name='fondo de la barra de anuncio'),
        ),
    ]
