# Generated by Django 6.0.6 on 2026-06-29 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0006_siteconfig_color_announce'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='announce_text',
            field=models.CharField(blank=True, default='Envío a todo el país · Atención cercana de lunes a sábado', max_length=160, verbose_name='texto de la barra de anuncio'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='color_text',
            field=models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator('^(?:#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6}))?$', 'Usa un color hexadecimal, p. ej. #0e6e4e.')], verbose_name='color del texto'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='font_body',
            field=models.CharField(default='inter', max_length=40, verbose_name='fuente del cuerpo'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='font_heading',
            field=models.CharField(default='fraunces', max_length=40, verbose_name='fuente de titulares'),
        ),
    ]
