# Generated by Django 6.0.6 on 2026-06-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0007_siteconfig_announce_text_siteconfig_color_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='announce_icon',
            field=models.CharField(blank=True, default='Truck', max_length=40, verbose_name='icono de la barra de anuncio'),
        ),
    ]
