# Generated by Django 6.0.6 on 2026-06-29 21:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0008_siteconfig_announce_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='announce_animation',
            field=models.CharField(choices=[('static', 'Estática'), ('marquee', 'Texto deslizante')], default='static', max_length=12, verbose_name='comportamiento de la barra'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='announce_icon_color',
            field=models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator('^(?:#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6}))?$', 'Usa un color hexadecimal, p. ej. #0e6e4e.')], verbose_name='color del icono de la barra'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='announce_speed',
            field=models.CharField(choices=[('slow', 'Lenta'), ('normal', 'Normal'), ('fast', 'Rápida')], default='normal', max_length=8, verbose_name='velocidad del deslizamiento'),
        ),
    ]
